### ISSUE TITLE
Alternative license for use as a library?

### ISSUE THREAD

**Issue by pombredanne** [philipmorrisintl/RPackUtils#1]
Hi:
I am considering reusing this fine library to report R packages in the scancode-toolkit licenses and packages scanner.
See https://github.com/nexB/scancode-toolkit/issues/1628 and https://github.com/nexB/scancode-toolkit/
ScanCode is Apache-licensed and not GPL-licensed.

I was wondering if I could talk you to offer an alternative license for library usage such as the LGPL or permissive license?
Thank you for you kind consideration!

**Comment by sgubianpm** [comment]
@pombredanne,
Thanks for you interest in our RPackUtils tool. We discussed this together with @scanopm (who is the maintainer and who did a nice refactoring, added new features and made it publishable) and we don't see any reason for not re-licensing this to a more permissive license. However, as we published that on behalf of the company we're working for, we need to check this quickly with the legal department. Will keep you updated as soon as we get the feedback from the legal people.
Best regards,

Sylvain.

**Comment by pombredanne** [comment]
@sgubianpm that extremely gentle of you to take the time to look into this ! And I am sure you appreciate the irony that scancode is itself a license detection tool

**Comment by sgubianpm** [comment]
@pombredanne, sure, I do appreciate it! Nice work!

**Comment by scanopm** [comment]
Hi Philippe,
First I thank you for your interest and I have to say we are using your **scancode-toolkit** and find it useful since most of the existing tools need some kind of package manager entry point in order to look into the dependencies and their licenses, mostly are not using any text analysis or any other kind of generic way that would work across all kind of projects and programming languages. I'm also thinking about projects using multiple languages.

This message is also to give an update, I have prepared RPackUtils and now it is in review.
It will take the necessary time and then a new release will be available with a more permissive license.

Kind regards,
Stephane.

**Comment by pombredanne** [comment]
@scanopm thank you ++ for the nice words and for following up on this!

**Comment by pombredanne** [comment]
gentle ping :) ... any update?

**Comment by scanopm** [comment]
RPackUtils is still in review and we had to check the license of some modules: direct and indirect dependencies of RPackUtils.
A tricky one was the LGPL **chardet**, which your Apache2 [scancode-toolkit](https://github.com/nexB/scancode-toolkit/) is using as well.

We can't give you any estimate on the required time it's going to take unfortunately.
With @sgubianpm, we both hope to be able to go forward with a new license very soon.

**Comment by pombredanne** [comment]
@scanopm thank you for the update!

You wrote:

>  A tricky one was the LGPL chardet, which your Apache2 scancode-toolkit is using as well.

FWIW the general community understanding (and something I saw mostly universally recognized by lawyers too) is that the LGPL copyleft does not extend to the libraries calling that LGPL code (as long as the LGPL code is used unmodified and with some caveats when there is static linking which is not a possibility in Python).

**Comment by scanopm** [comment]
Hi Philippe,

I'm glad we can finally address your request and announce **RPackUtils** has been re-licensed to _Apache 2.0_

With Sylvain and my colleagues, we thank you again for your interest and your patience!

Sincerely,
Stephane.

**Comment by pombredanne** [comment]
Thank you very much. This is great! :bowing_man:
